name: Wunsch / Verbesserung
about: Vorschlag für die Übersetzung oder das Projekt
labels: [enhancement]
body:
  - type: textarea
    id: request
    attributes:
      label: Vorschlag
      description: Beschreibe deinen Wunsch möglichst konkret.
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Warum wäre das hilfreich?
